In [1]:
#넘파이 배열은 속도가 빠름, 적은 메모리 차지, 같은 자료형, 원소의 개수 변경 불가
#리스트는 속도가 느림, 메모리 차지 많음, 자료형이 달라도 됨, 원소의 개수가 변경

In [ ]:
#넘파이 : 배열이 구현되어 있는 패키지 -> 수치연산(벡터, 행렬 연산)

In [3]:
import numpy as np

In [5]:
np.array([1,2,3,4]) #array함수에 리스트를 넣음, 1차원 배열
type(np.array([1,2,3,4]))

numpy.ndarray

In [6]:
# 벡터화연산 : 배열의 각 원소에 대한 반복 연산을 
# 명령어 1개로 처리

In [7]:
# [1,2,3,4] -> [2,3,4,5] : 파이썬의 경우 4번 연산
# [1,2,3,4] -> [2,3,4,5] : 넘파이의 경우 1번 연산

In [13]:
#파이썬 연산
ans=[]
data=[1,2,3,4]
for i in data:
    ans.append(i+1)
ans

[2, 3, 4, 5]

In [14]:
#넘파이 연산
np.array(data)
np.array(data)+1
np.array(data)*3

array([ 3,  6,  9, 12])

In [15]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [24]:
x*y #요소간 곱셈
2*x+y
x == y #요소간 비교연산
x > 2
(x>2) & (y>4) #and

array([False, False,  True])

In [25]:
#브로드캐스팅 : 손오공

In [32]:
#1차원 배열 : 벡터
#2차원 배열 : 행렬

#2*3배열
x=np.array([[1,2,3],[4,5,6]])

In [37]:
len(x) #행의 개수
len(x[0]) #열의 개수

3

In [38]:
x=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
# x배열의 깊이 : 2
# x배열의 행 : 2
# x배열의 열 : 3
# x : 2*2*3 배열

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [46]:
x=np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])

# 3차원배열x = [행렬1, 행렬2]
# x[0]=행렬1
# x[1]=행렬2
# x[0][0]=행렬1의 첫번째 행

# x배열의 깊이 : 2
# x배열의 행 : 3
# x배열의 열 : 4
# x배열의 shape? 2*3*4 배열
len(x) #깊이
len(x[0]) #행
len(x[0][0]) #열

4

In [49]:
x.ndim #배열의 차원
x.shape    #shape(배열의 크기)

(2, 3, 4)

In [50]:
x=np.array([1,2,3])

In [54]:
x[-1]

3

In [68]:
x=np.array([[1,2,3],
[4,5,6]])
x
x[0]#첫번째 행 출력
x[1]
x[-1] #마지막 행으로부터 거꾸로 참조
x[-2]

x[0][0]#첫번째 행의 첫번째 열 출력
x[-2][0]
x[-2][-3]
x[0,0] #컴마를 이용한 접근도 가능. 컴마로 구분된 차원을 축(axis)라고 함

x[-1][-1]

6

In [78]:
x=np.array([[1,2,3],
[4,5,6]])

x[0] #첫번째 행 전체
x[0,] #x[행,열], #첫번째 행 전체
x[0, : ] ##첫번째 행 전체

x[1]
x[1, :]

x[:,1]   #x[행,열]

array([2, 5])

In [84]:
# array([5, 6])출력
x[1][1:]
x[1,1:]
x[1][1:3]
x[-1][-2:]

array([5, 6])

In [85]:
# array([[2, 3]
#        [5, 6]])출력

In [89]:
x[:,1:]
x[:,-2:]  #x[행,열]   :은 범위,   시작인덱스:끝인덱스(포함안됨)

array([[2, 3],
       [5, 6]])

In [90]:
#불린참조, 불린값(True/False)으로 구성된 배열로 참조,
#주의:참조 대상 배열(x)과 불린 배열(b)의 크기가 동일

In [91]:
x=np.array([1,2,3])
b=np.array([True, False, True])

In [94]:
x[b] #True 에 해당되는 자료가 추출

array([1, 3])

In [96]:
x>1
x[x>1]

array([2, 3])

In [105]:
x=np.array([1,2,3])
#b=np.array([True, False, True, True])
#b=np.array([True, False, True])
x%2==1

array([ True, False,  True])

In [106]:
x[x%2==1] 

array([1, 3])

In [109]:
x=np.array([10,20,30,40,50])
#y=np.array([0,2,4])
y=np.array([0,2,4,0,0,2])

In [110]:
#정수 배열 인덱싱
x[y]

array([10, 30, 50, 10, 10, 30])

In [111]:
x=np.array([[10,20,30],[40,50,60]])
x

array([[10, 20, 30],
       [40, 50, 60]])

In [114]:
x[ : ,[True,False,True]] #0번 2번 index 열 데이터 추출
x[[True,False],:]  #0번 index 행 데이터 추출

array([[10, 20, 30]])

In [115]:
x[:]

array([[10, 20, 30],
       [40, 50, 60]])

In [124]:
x[ : , [0,2]]
x[ : , [2,0]]
x[ : , [2,0,0,2,0]]
x[[1,1,1,0],:]
x[[1,0],:]

array([[40, 50, 60],
       [10, 20, 30]])

In [127]:
x= np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [143]:
x
# 7참조
x[1 ,2]
x[x==7]
# 14참조
x[-1, -1]
# [6,7]참조
x[1,1:3]
x[1,[1, 2]]
x[(x==6)|(x==7)]
# [7,12]참조
x[1:,2]
x[1:3,2]

# [[3,4],[8,9]]
x[0:2,3:5]


array([[3, 4],
       [8, 9]])

In [144]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [145]:
# 3의 배수 출력
# 4로 나누었을때 나머지가 1인 값을 출력
# 3으로 나누어지고 4로 나누면 나머지가 1인 값을 출력
x[x%3==0]
x[x%4==1]
x[(x%3==0) & (x%4==1)]


array([9])

In [154]:
x=np.array([1, 2.5])

In [153]:
type(x)

#배열에 저장된 자료 타입 확인
x.dtype

dtype('int32')

In [159]:
x=np.array([1, 2.5], dtype='i') #dtype:f
x.dtype
x

array([1, 2], dtype=int32)

In [160]:
#Inf   
#Infinity, NaN(not a number)

In [162]:
np.inf #무한대를 표현하는 상수
np.nan #정의할 수 없는 숫자 

nan

In [171]:
print(np.array([1]) / np.array([0])) #inf
print(np.array([0]) / np.array([1])) #0
print(np.array([-1]) / np.array([0]))
print(np.array([0]) / np.array([0]))

print(np.log(0))
print(np.exp(-np.inf))


[inf]
[0.]
[-inf]
[nan]
-inf
0.0


<ipython-input-171-20aea313548d>:1: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([1]) / np.array([0])) #inf
<ipython-input-171-20aea313548d>:3: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([-1]) / np.array([0]))
<ipython-input-171-20aea313548d>:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.array([0]) / np.array([0]))
<ipython-input-171-20aea313548d>:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(0))


In [172]:
np.zeros(3)

array([0., 0., 0.])

In [174]:
np.zeros((3,2))
np.zeros((3,2,4)) #(깊이,행,열)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [175]:
np.zeros((3,2,4),dtype='i')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [176]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [180]:
#np.ones((2,3,4))*999

In [184]:
x=np.zeros(5, dtype='U4')
x[0]="test"
x

array(['test', '', '', '', ''], dtype='<U4')

In [185]:
#https://numpy.org/

In [186]:
x=np.ones((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [190]:
y=np.ones_like(x, dtype='i')
#zeros(ones)_like함수 : x배열의 크기와 동일하게 0 또는 1로 모두 초기화하여 생성
y

#np.ones_like(x, dtype='i') 작업을 하면 컴퓨터 내부에서는 어떤 일이?
#x배열 크기 확인 -> x배열 크기와 동일한 배열 공간 생성 -> 1로 모두 초기화

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [192]:
np.empty((3,2)) 
#zeros:0으로 초기화, empty:기존에 메모리에 남아있는 쓰레기값으로 초기화

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [195]:
np.array(list(range(8)))

array([0, 1, 2, 3, 4, 5, 6, 7])

In [196]:
np.array(list(range(8))).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [198]:
np.arange(8) #np.array(list(range(8)))
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [200]:
np.arange(1,11) 
np.arange(1,11,2) 

array([1, 3, 5, 7, 9])

In [201]:
np.linspace(0, 100, 10) #선형 구간, 시작, 끝, 개수

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [204]:
#np.logspace(시작, 끝, 개수, base)#로그 스케일 값으로 배열 생성

np.logspace(start=1,stop=10,num=10) #base가 생략(기본값 10)
np.logspace(start=1,stop=10,num=10, base=10) 

np.logspace(start=1,stop=10,num=10, base=2)  #base가 2

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [205]:
#전치행렬:행과열을 바꾸어놓은 행렬, T속성을 이용

In [207]:
#1~6까지 2행3열 행렬생성
X=np.arange(1,7).reshape((2,3))

In [209]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#엘리먼트 와이즈 프로덕
#element wise product : 요소간 곱셈 연산

#닷 프로덕, 매트릭스 멀티플라이(행렬의 곱셈)
#dot product, matrix multiply


In [212]:
x=np.arange(12)
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [216]:
x=np.arange(12)
x.reshape(3,-1)
x.reshape(4, -1)
x.reshape(-1, 2) #열은 2개, 행은 네가 계산해서 알아서 해

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [221]:
x=np.arange(24)
x
x.reshape(2,3,-1)
x.reshape(2,-1, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
#reshape으로 차원을 증가시킬 수 있다
#ex) reshape함수 : 1차원 배열 -> 다차원 배열

#ex) flatten 또는 ravel함수 : 다차원 배열 -> 1차원 배열

In [226]:
x=x.reshape(2,3,-1)
x.shape
x.ndim

3

In [227]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [228]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [229]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [230]:
import pandas as pd

In [232]:
df=pd.read_csv("samsung.csv")
df

Date   Open   High    Low  Close    Adj Close    Volume
0    2020-07-28  57000  58800  56400  58600  56560.60547  48431566
1    2020-07-29  60300  60400  58600  59000  56946.68750  36476611
2    2020-07-30  59700  60100  59000  59000  56946.68750  19285354
3    2020-07-31  59500  59600  57700  57900  55884.96875  21943345
4    2020-08-03  57800  57900  56700  56800  54823.25000  21158940
..          ...    ...    ...    ...    ...          ...       ...
244  2021-07-22  79000  79800  78900  79700  79700.00000  12618790
245  2021-07-23  79700  79900  79200  79300  79300.00000   9098910
246  2021-07-26  79400  79500  78800  78800  78800.00000  10040975
247  2021-07-27  79200  79400  78500  78500  78500.00000  11427693
248  2021-07-28  78300  78900  78100  78400  78400.00000  10199591

[249 rows x 7 columns]

In [242]:
samsung=np.loadtxt("samsung.csv", skiprows=1, delimiter=',') #첫번째 줄 스킵
samsung.shape
samsung
#samsung 변수에 담긴 배열을 이용하여 오늘 학습한 함수, 열, 행 추출


array([[   57000.     ,    58800.     ,    56400.     ,    58600.     ,
           56560.60547, 48431566.     ],
       [   60300.     ,    60400.     ,    58600.     ,    59000.     ,
           56946.6875 , 36476611.     ],
       [   59700.     ,    60100.     ,    59000.     ,    59000.     ,
           56946.6875 , 19285354.     ],
       ...,
       [   79400.     ,    79500.     ,    78800.     ,    78800.     ,
           78800.     , 10040975.     ],
       [   79200.     ,    79400.     ,    78500.     ,    78500.     ,
           78500.     , 11427693.     ],
       [   78300.     ,    78900.     ,    78100.     ,    78400.     ,
           78400.     , 10199591.     ]])

In [243]:
#kaggle.com

In [254]:
df=pd.read_csv("train.csv")
df['Name']
df['Name'][0]
df['Name'][1]
df['Name'][890]

'Dooley, Mr. Patrick'

In [251]:
len(df['Name'])

891

In [261]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [ ]:
#모든 호칭 추출하여 저장
#호칭 종류가 몇가지 출력
#호칭 종류별 승객수 출력
# ex) Mr : 500명
#     Mrs : 400명
#         ...
        