In [ ]:
#벡터의 크기와 방향은 좌표축 성분으로 나누어 표현

In [1]:
import numpy as np

In [11]:
arr = np.array(list(range(30))).reshape(5, -1)
d_np = np.arange(30.).reshape(5, 6)
np.max(arr)

#각 행의 합
arr.sum(axis = 1)
#각 행의 최댓값
np.max(arr, axis = 1)
#각 열의 평균
arr.mean(axis = 0)
#각 열의 최솟값
print(np.min(arr, axis = 0))



[0 1 2 3 4 5]


In [12]:
print(d_np)
print(d_np.max()) #np.max(d_np)
print(d_np.sum(axis=1)) #행
print(d_np.max(axis=1)) #행
print(d_np.mean(axis=0)) #열
print(d_np.min(axis=0)) #열


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]
29.0
[ 15.  51.  87. 123. 159.]
[ 5. 11. 17. 23. 29.]
[12. 13. 14. 15. 16. 17.]
[0. 1. 2. 3. 4. 5.]


In [13]:
arr = np.array(list(range(30))).reshape(5, -1)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [14]:
#정렬: axis=0 -> 행을 정렬,  axis=1 ->열을 정렬

In [16]:
arr.sort(axis=1)

In [17]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [19]:
arr=np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
arr

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [20]:
arr.sort(axis=1) #행을 기준으로 정렬

In [21]:
arr

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [22]:
arr.sort(axis=0) #열을 기준으로 정렬, in-place메서드

In [23]:
arr

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [24]:
x=np.argsort([40,30,10,20])
x

array([2, 3, 1, 0], dtype=int64)

In [25]:
data=[70,91,69,78,82]

In [29]:
# 기술통계
len(data)
sum(data)/len(data)
np.mean(data)

78.0

In [30]:
#분산?데이터와 평균값 사이의 거리에 대한 제곱의 평균
#분산이 작다? 데이터가 모여있다

#표준편차? 분산의 제곱근

In [31]:
# def myVar(data):
    
#     return 분산
# def myStd(data):
    
#     return 표준편차

def myVar(data):
    average = sum(data) / len(data)
    dists = [(d - average) ** 2 for d in data]
    return sum(dists) / len(dists)

def myStd(data):
    return myVar(data) ** 0.5


In [32]:
data=[70,91,69,78,82]

In [34]:
myVar(data)
myStd(data)

8.12403840463596

In [35]:
import math

def myVar(data):
    for i in data:
        var = (i-np.mean(data))**2/len(data)
    return var

def myStd(data):
    var = myVar(data)
    std = math.sqrt(var)
    return std


In [36]:
data=[70,91,69,78,82]

In [38]:
np.var(data)
np.std(data)

8.12403840463596

In [39]:
np.median(data)

78.0

In [40]:
#사분위수: 데이터를 오름차순정렬
# 1사분위수 : 1/4위치에(하위 25%) 있는 수
# 2사분위수 : 2/4위치에(median) 있는 수
# 3사분위수 : 3/4위치에(하위 75%) 있는 수
# 최대값(4/4위치)

In [41]:
np.random.seed(802)

In [42]:
#seed(802):씨앗
# np.random.rand:0~1 난수 생성
# np.random.randn:표준정규분포 난수 생성, 평균:0, 표준편차:1
# np.random.randint:정수 난수 생성

np.random.randint(10)

0

In [45]:
np.random.randint(1, 10, 5) #1~10까지 5개의 난수 생성
#1<=난수<10

array([4, 9, 5, 3, 1])

In [48]:
#표준편차가 30 =>  평균과 차이가 크다
#단위를 고려
x=[173, 181, 168, 175, 179]
y=[1.73, 1.81, 1.68, 1.75, 1.79]
np.var(x) #분산이 20.96
np.var(y) #분산이 0.002

#수학 분산/표준편차, 국어 분산/표준편차

0.0020960000000000037

In [ ]:
#머신러닝할때 데이터의 단위가 다른것이 뒤섞여 있는 경우가 있음
#=> 표준값(Z값) = (신장데이터 - 신장평균) / 신장표준편차

In [49]:
# 국어점수평균 80점 => 90점, 표준편차:5 => 표준값 : 2
# 수학점수평균 50점 => 70점, 표준편차:4 => 표준값 : 5
#         신장   몸무게   나이
# 사람1   170      60      20
# 사람2   169      59      25
# 사람3   170      64
#         169      62 
# ...
# 사람n




# 사람1과 가장 비슷한 사람?
# 신장 범위 : 150 ~ 190
# 몸무게 범위 : 40 ~ 150
# 나이 범위 : 20~29



In [50]:
x=np.random.randint(1, 100, 30)
x

array([ 6, 68, 34,  1, 75, 68, 29, 28, 73, 71, 56, 69, 52, 82, 60, 96, 21,
       89, 93, 10, 24, 28, 79, 55,  3, 51, 23, 77, 81, 20])

In [53]:
np.percentile(x, 25) #percentile:백분위수
np.percentile(x, 50) #percentile:백분위수
np.percentile(x, 75) #percentile:백분위수
np.percentile(x, 100) #percentile:백분위수

96.0

In [55]:
np.random.randint(10,20,size=(3,5))

array([[14, 15, 10, 15, 19],
       [12, 13, 18, 18, 13],
       [14, 15, 12, 15, 14]])

In [56]:
np.unique([1,1,2,2,3])

array([1, 2, 3])

In [57]:
np.unique([1,1,2,2,3], return_counts=True)

(array([1, 2, 3]), array([2, 2, 1], dtype=int64))

In [59]:
np.unique([1,1,2,2,3], return_counts=True)[0]
np.unique([1,1,2,2,3], return_counts=True)[1]

array([2, 2, 1], dtype=int64)

In [60]:
a, b=np.unique([1,1,2,2,3], return_counts=True)
print(a)
print(b)

[1 2 3]
[2 2 1]


In [70]:
#np.bincount([1,1,2,2,3]) #0부터 3까지 각 수에 대한 카운트 값

#주사위
np.bincount([1,1,2,2,3],minlength=7)
#0번은 버림

array([0, 2, 2, 1, 0, 0, 0], dtype=int64)